URL_SERVICE = "https://cnt-2dd64419-92ea-43fa-8c44-4825c3c2d757.containerhub.tripleten-services.com/"
DOC_PATH = "/docs/"
LOG_MAIN_PATH = "/api/logs/main/"
USERS_TABLE_PATH = "/api/db/resources/user_model.csv"
CREATE_USER_PATH = "/api/v1/users/"
PRODUCTS_KITS_PATH = "/api/v1/products/kits/"
